from pathlib import Path
import sys
import json
from html import escape

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent
ROOT.mkdir(parents=True, exist_ok=True)
ORIGIN = 'https://aimdownloader.pages.dev'
REPO = 'https://github.com/malikali4129/AIM-DOWNLOADER-RELEASE'
EMAIL = 'business.aliimranmalik@gmail.com'
# Change this single value and regenerate the committed HTML to update availability copy.
AVAILABILITY = 'Free to download for now'

def write(name, text):
    path = ROOT / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')

def icon(name='arrow'):
    paths = {'arrow':'M7 17 17 7M7 7h10v10', 'download':'M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5', 'play':'m9 5 11 7-11 7Z', 'queue':'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01', 'audio':'M4 10v4m4-8v12m4-15v18m4-15v12m4-8v4', 'check':'m5 12 4 4L19 6', 'windows':'M3 4l8-1v8H3Zm10-1 8-1v9h-8ZM3 13h8v8l-8-1Zm10 0h8v9l-8-1Z'}
    return f'<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="{paths[name]}"/></svg>'

def brand():
    return '<a class="brand" href="/" aria-label="AIM Downloader home"><img src="/assets/brand-icon.png" width="44" height="44" alt=""><span>AIM<span class="brand-small">DOWNLOADER</span></span></a>'

def button(text, href='/download/', primary=True, extra=''):
    return f'<a class="button {"primary" if primary else "secondary"}" href="{href}" {extra}>{icon("download" if primary else "arrow")}<span>{text}</span></a>'

def github_fallback():
    return f'<a class="text-link" href="{REPO}/releases/latest">View downloads on GitHub {icon()}</a>'

def heading(kicker, title, desc):
    return f'<header class="page-heading"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{desc}</p></header>'

def page(route, title, desc, content):
    nav = [('Home','/'),('Download','/download/'),('Getting started','/getting-started/'),('FAQ & support','/support/'),('Releases','/releases/')]
    links = ''.join(f'<a href="{url}" {"aria-current=page" if url==route else ""}>{name}</a>' for name,url in nav)
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} · AIM Downloader</title><meta name="description" content="{desc}"><meta name="theme-color" content="#0D0E12"><link rel="canonical" href="{ORIGIN}{route}"><meta property="og:title" content="{title} · AIM Downloader"><meta property="og:description" content="{desc}"><meta property="og:type" content="website"><meta property="og:url" content="{ORIGIN}{route}"><meta name="twitter:card" content="summary"><link rel="icon" type="image/png" href="/assets/brand-icon.png"><link rel="stylesheet" href="/assets/styles.css"><script type="module" src="/assets/app.js"></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><div class="site-header"><div class="nav-wrap">{brand()}<button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">{links}</nav><a class="nav-download" href="/download/">Get AIM {icon('download')}</a></div></div>
<main id="main" tabindex="-1">{content}</main>
<footer><div class="footer-top">{brand()}<p>Your media. Your way.<br><span>A downloader made for Windows.</span></p><a href="mailto:{EMAIL}" class="text-link">Let’s talk {icon()}</a></div><div class="footer-bottom"><span>© 2026 Ali Imran Malik</span><div><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/license/">License</a><a href="/cookies/">Cookies</a><a href="/legal/">Notices</a><a href="/support/">Support</a><a href="{REPO}/issues">Report an issue</a><a href="{REPO}/releases">GitHub releases {icon()}</a></div><span class="availability">{AVAILABILITY}</span></div></footer></body></html>'''

home = f'''<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> MADE FOR WINDOWS · BUILT AROUND YOU</p><h1>Your media.<br>Your <span class="pink">way.</span></h1><p class="lead">Videos, playlists, and audio.<br>Bring them together in one thoughtfully simple downloader.</p><div class="actions">{button('Download for Windows')}{button('See how it works', '#how-it-works', False)}</div><p class="micro">Windows 10 / 11 · 64-bit <span>•</span> {AVAILABILITY}</p></div><div class="hero-mark" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><img src="/assets/brand-icon.png" width="400" height="400" alt=""><span class="mark-caption">LESS FRICTION. MORE PLAY.</span></div></section>
<section class="product-section wrap" aria-labelledby="product-title"><div class="section-top"><div><p class="eyebrow">MEET YOUR NEW DOWNLOAD SPACE</p><h2 id="product-title">Everything in its place.</h2></div><p>One queue. Clear progress.<br>You’re in control from start to finish.</p></div><a class="app-shot" href="/assets/app-screenshot.jpg" aria-label="View full-size screenshot of AIM Downloader"><img src="/assets/app-screenshot.jpg" width="1160" height="780" alt="AIM Downloader desktop application showing its download workspace" fetchpriority="high"></a><div class="screenshot-caption"><span><span class="status-dot"></span> THE AIM DOWNLOADER DESKTOP APP</span><a href="/getting-started/">Take a closer look {icon()}</a></div></section>
<section class="features wrap"><div class="section-top"><div><p class="eyebrow">YOUR LINKS. MORE POSSIBILITIES.</p><h2>One app. All the essentials.</h2></div><a class="text-link" href="/download/">Find your download {icon()}</a></div><div class="feature-grid"><article><span class="feature-icon">{icon('play')}</span><span class="feature-no">01 / VIDEO</span><h3>Keep the quality.</h3><p>Save video in the available quality you choose. Keep original codecs, or choose a compatible MP4 format when available.</p></article><article><span class="feature-icon">{icon('queue')}</span><span class="feature-no">02 / PLAYLISTS</span><h3>Make room for more.</h3><p>Analyze a playlist, choose the entries you want, and add them to your queue. Keep track of each download in one place.</p></article><article><span class="feature-icon">{icon('audio')}</span><span class="feature-no">03 / AUDIO</span><h3>Just the sound.</h3><p>Extract original audio or convert it to MP3. A straightforward way to keep the audio you want from supported media.</p></article></div><div class="feature-strip"><span>{icon('check')} Pause & resume</span><span>{icon('check')} Duplicate handling</span><span>{icon('check')} Installer or portable</span><span>{icon('check')} Automatic tool setup</span></div></section>
<section class="how wrap" id="how-it-works"><div><p class="eyebrow">FROM LINK TO LIBRARY</p><h2>Three steps.<br>Then it’s yours.</h2><a class="text-link" href="/getting-started/">Read the getting started guide {icon()}</a></div><ol class="steps"><li><span>01</span><div><h3>Choose your format.</h3><p>Pick a video or audio preset. Turn Auto-Download off to review items first.</p></div></li><li><span>02</span><div><h3>Paste your link.</h3><p>Add your public media link and choose playlist entries in review mode.</p></div></li><li><span>03</span><div><h3>Let AIM take it from here.</h3><p>Start your pending downloads, follow their progress, and open the finished files.</p></div></li></ol></section>
<section class="cta wrap"><div><p class="eyebrow">READY WHEN YOU ARE</p><h2>Your next download<br>starts here.</h2><p>{AVAILABILITY}. Made for Windows.</p></div>{button('Get AIM Downloader')}</section>'''

download = heading('GET AIM DOWNLOADER', 'A little setup.<br><span class="pink">A lot to keep.</span>', 'Choose how you want to run AIM. The installer is the easiest place to start.') + f'''<section class="wrap"><div class="release-status" role="status" data-release-status>Get the latest stable version from GitHub Releases.</div><div class="download-grid"><article class="download-card recommended"><div class="card-top"><span class="feature-icon">{icon('windows')}</span><span class="pill">RECOMMENDED</span></div><h2>Windows installer</h2><p>Install AIM for your Windows account, with Start menu access and an optional desktop shortcut.</p><div class="asset-info" data-asset-info="installer">Windows 10 / 11 · x64 · .exe</div><a class="button primary" data-asset="installer" hidden>{icon('download')}<span>Download installer</span></a><p class="asset-missing" data-missing="installer" hidden>Installer not included in this release.</p><div class="fallback">{github_fallback()}</div></article><article class="download-card"><div class="card-top"><span class="feature-icon">{icon('download')}</span><span class="pill muted">NO INSTALLATION</span></div><h2>Portable edition</h2><p>Extract the ZIP into a writable folder and run AIM directly. Keep the application and its data together.</p><div class="asset-info" data-asset-info="portable">Windows 10 / 11 · x64 · .zip</div><a class="button secondary" data-asset="portable" hidden>{icon('download')}<span>Download portable ZIP</span></a><p class="asset-missing" data-missing="portable" hidden>Portable ZIP not included in this release.</p><div class="fallback">{github_fallback()}</div></article></div><div class="download-meta"><p>{AVAILABILITY}. No separate .NET or Python installation needed.</p><a data-asset="checksums" class="text-link" hidden>SHA-256 checksums {icon()}</a></div><noscript><p class="notice">Live version details need JavaScript. Use the GitHub links above to choose your download.</p></noscript></section><section class="wrap split-section"><div><p class="eyebrow">BEFORE YOU START</p><h2>Made for your<br>Windows desktop.</h2></div><dl class="requirements"><div><dt>Operating system</dt><dd>Windows 10 or Windows 11, 64-bit (x64).</dd></div><div><dt>Connection</dt><dd>Internet access for initial tool setup and media downloads.</dd></div><div><dt>Storage</dt><dd>A writable app location and enough free space for your media and temporary processing files.</dd></div><div><dt>First launch</dt><dd>AIM sets up yt-dlp, FFmpeg, and Deno. Let setup finish before adding your first download.</dd></div></dl></section><section class="wrap note-panel"><h3>A good place to start.</h3><p>New to AIM? Follow the short setup guide, then try your first link.</p><a class="text-link" href="/getting-started/">Open the guide {icon()}</a></section>'''

guide = heading('GETTING STARTED','From first launch<br>to <span class="pink">first download.</span>','A short guide to getting comfortable with AIM Downloader.') + '''<div class="wrap guide-layout"><aside class="guide-index"><p class="eyebrow">IN THIS GUIDE</p><a href="#install">01 · Install or extract</a><a href="#setup">02 · Complete setup</a><a href="#link">03 · Add your links</a><a href="#formats">04 · Choose your format</a><a href="#queue">05 · Manage your queue</a><a href="#files">06 · Find your files</a></aside><div class="guide-content">
<section id="install"><span class="step-label">01 / GET THE APP</span><h2>Install. Or just extract.</h2><p>Download the Windows installer and follow its prompts. It installs for your account and can add a desktop shortcut.</p><p>Prefer the portable edition? Extract the complete ZIP into a writable folder, then open <code>AIM-DOWNLOADER.exe</code>. Keep the extracted files together.</p><a href="/download/" class="text-link">Choose your download →</a></section>
<section id="setup"><span class="step-label">02 / FIRST LAUNCH</span><h2>Give AIM a place to work.</h2><p>Follow the welcome steps, choose your download folder, and let automatic tool setup complete. AIM downloads and verifies the tools it needs for supported media.</p><p>Keep your internet connection active. If setup is interrupted, use Retry. You do not need to install Python or .NET separately.</p></section>
<section id="link"><span class="step-label">03 / ADD YOUR MEDIA</span><h2>It starts with a link.</h2><p>Choose your quality preset and duplicate policy first. Turn Auto-Download off if you want to review items before they start. Then paste a public video or playlist URL and add it to AIM. With Auto-Download off, playlists open a selection window so you can choose the entries to keep.</p><p>With Auto-Download on, added links start immediately and playlist entries are queued automatically. You can also import a text file of URLs. Private, account-only, and cookie-dependent media are outside the supported workflow.</p></section>
<section id="formats"><span class="step-label">04 / MAKE IT YOURS</span><h2>Choose video or audio.</h2><p>Choose the available quality and format before queueing. Source media determines which options are available.</p><ul><li><strong>Best video:</strong> preserves the original codecs and merges video and audio without re-encoding video.</li><li><strong>MP4 compatible:</strong> uses compatible H.264/AAC formats when the source offers them.</li><li><strong>Original audio:</strong> extracts the source audio.</li><li><strong>MP3:</strong> converts the audio to MP3.</li></ul><p>Choose a preset before adding links. Available results depend on the source; selecting a higher quality cannot create a format the source does not offer.</p></section>
<section id="queue"><span class="step-label">05 / FOLLOW THE PROGRESS</span><h2>Keep your queue moving.</h2><p>Add selected items to the queue. AIM uses three simultaneous download slots by default; you can adjust concurrency in Settings. Use Pause and Resume / Retry as needed; some sources may restart transfers.</p><p>Pause is unavailable while files are merging or converting. Cancel stops the current job and removes its temporary staging files.</p><p>For duplicate files, choose Skip, Keep both, or Replace based on what you want to keep.</p></section>
<section id="files"><span class="step-label">06 / ENJOY THE RESULT</span><h2>Right where you left them.</h2><p>Open a completed file or its output folder from the queue. Your chosen download folder contains the finished media.</p><p>Removing a queue record does not delete its completed file. Keep enough free disk space for both your downloads and temporary processing.</p><div class="notice">Only download media you have permission to save.</div></section></div></div>'''

faqs = [
('Is AIM free?', f'{AVAILABILITY}. There are no purchasing or account steps on this website. Availability may change in the future.'),
('Which systems can run it?', 'AIM is a Windows x64 desktop application. Use Windows 10 or Windows 11. macOS and Linux editions are not available.'),
('What is the difference between installer and portable?', 'The installer adds AIM to your Windows account with Start menu access. The portable ZIP runs from an extracted writable folder and keeps its data alongside the application.'),
('Which sites and links work?', 'AIM uses yt-dlp for supported public video and playlist links. Support depends on each source and can change. Private, login-only, and cookie-dependent media are outside the supported workflow.'),
('Why does the first launch download tools?', 'AIM uses yt-dlp for media extraction, FFmpeg / FFprobe for media processing, and Deno for JavaScript support. First-run setup downloads and verifies these tools automatically.'),
('Setup failed. What should I do?', 'Check your internet connection, confirm the app and download folders are writable, and retry setup. A checksum failure prevents that tool download from being activated. Report repeated failures through support.'),
('Can I pause a download?', 'Yes, during downloading. Pause retains partial files, and Resume / Retry attempts the transfer again. Some sites restart downloads. Merging and conversion stages cannot be paused.'),
('Why is a format or quality missing?', 'Available formats depend on the source. Choose a quality preset before adding a link; source formats determine the final result. MP4 compatibility requires the source to offer compatible codecs.'),
('What happens to duplicate downloads?', 'Choose Skip to avoid known duplicates, Keep both to save numbered filenames, or Replace to replace the existing completed file after the new result is ready.'),
('How do I get updates?', 'AIM checks the public GitHub release channel for app updates. You can also visit the Downloads or Releases page at any time. Tool updates are managed separately inside the app.'),
('Does this website process my media?', 'No. This website provides product information and links to GitHub downloads. Media analysis and downloads happen in the Windows application. The website has no account system or media-upload form. See the Privacy Policy for hosting and network-request details.'),
('Can I use any video I find?', 'Download only media you have permission to save. Respect the source website’s terms and the rights of content owners.')]
support = heading('FAQ & SUPPORT', 'A little help.<br><span class="pink">A clear next step.</span>', 'Answers to the common questions, and a direct line when you need a hand.') + '<section class="wrap support-layout"><div class="faq-list">' + ''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in faqs) + f'''</div><aside class="support-card"><span class="eyebrow">STILL NEED A HAND?</span><h2>Let’s sort it out.</h2><p>For bugs, include your AIM version, Windows version, and the error you see. Leave out passwords and private links.</p><a class="button secondary" href="{REPO}/issues">{icon()}Report an issue</a><div class="support-email"><span>Email support</span><a href="mailto:{EMAIL}">{EMAIL}</a></div><p class="micro">GitHub issues are public. Email is also available for support.</p></aside></section>'''

releases = heading('RELEASE NOTES', 'Always moving<br><span class="pink">forward.</span>', 'The latest stable releases, direct from the official AIM Downloader release channel.') + f'''<section class="wrap releases-wrap"><div class="release-status" data-release-status role="status">Browse the official releases on GitHub.</div><div data-release-list class="release-list"></div><div class="release-fallback">{button('Browse all releases', REPO+'/releases', False)}<p>Each release includes its available downloads, checksums, and full notes.</p></div><noscript><p class="notice">JavaScript is off. The GitHub link above includes the complete release history.</p></noscript></section><section class="wrap note-panel"><p class="eyebrow">ONE OFFICIAL CHANNEL</p><h2>The same releases your app checks.</h2><p>Website downloads and in-app update checks use the public AIM-DOWNLOADER-RELEASE repository.</p><a class="text-link" href="/download/">Choose installer or portable {icon()}</a></section>'''

pages = [('/', 'Your media. Your way.', 'Download public videos, playlists, and audio with AIM Downloader for Windows. Choose the installer or portable edition.', home),('/download/','Download for Windows','Get the AIM Downloader Windows installer or portable ZIP, with the latest release details and checksums.',download),('/getting-started/','Getting started','Install AIM Downloader, complete tool setup, choose formats, and manage your first media downloads.',guide),('/support/','FAQ & support','Find answers about AIM Downloader and contact support by email or public GitHub issues.',support),('/releases/','Releases','Explore stable AIM Downloader releases and their official GitHub download assets and release notes.',releases)]

# Legal content remains part of the static build; no Python runs in the browser.
legal_docs = json.loads((Path(__file__).resolve().parent / 'legal-content.json').read_text(encoding='utf-8'))
for doc in legal_docs:
    body = '<nav class="legal-nav" aria-label="Legal documents">' + ''.join(f'<a href="{d["route"]}">{escape(d["title"])}</a>' for d in legal_docs) + '</nav>'
    body += '<p class="legal-date">Last updated: 12 September 2026</p>'
    for number, (title, paragraphs) in enumerate(doc['sections'], 1):
        body += f'<section><h2>{number}. {escape(title)}</h2>' + ''.join(f'<p>{escape(p)}</p>' for p in paragraphs) + '</section>'
    if doc.get('license_file'):
        license_text = (Path(__file__).resolve().parent.parent / doc['license_file']).read_text(encoding='utf-8')
        body += '<p>Terms supplied with a particular release govern that release. This page does not retroactively replace earlier license grants.</p><pre class="license-text">' + escape(license_text) + '</pre>'
    if doc['route'] == '/privacy/':
        body += '<section><h2>Provider privacy policies</h2><ul><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a></li><li><a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub</a></li><li><a href="https://privacy.microsoft.com/privacystatement">Microsoft</a></li></ul></section>'
    body += '<p>Contact: <a href="mailto:' + EMAIL + '">' + EMAIL + '</a></p>'
    content = heading('PRIVACY & LEGAL', escape(doc['title']), escape(doc['description'])) + '<article class="wrap legal-content">' + body + '</article>'
    pages.append((doc['route'], doc['title'], doc['description'], content))

for route,title,desc,content in pages:
    write(('index.html' if route=='/' else route.strip('/')+'/index.html'), page(route,title,desc,content))
write('404.html', page('/404.html','Page not found','This page could not be found. Return to AIM Downloader.',heading('404 / WRONG TURN','This link took<br>a <span class="pink">detour.</span>','The page may have moved, but your next download is still within reach.')+f'<div class="wrap actions error-actions">{button("Back to home","/",False)}{button("Get AIM Downloader")}</div>'))
write('robots.txt', f'User-agent: *\nAllow: /\nDisallow: /scripts/\nDisallow: /tests/\nSitemap: {ORIGIN}/sitemap.xml\n')
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{ORIGIN}{r}</loc></url>' for r,*_ in pages)+'</urlset>\n')
print(f'Generated {len(pages)} pages, 404, robots.txt, and sitemap in {ROOT}')

